[2023-05-23 10:38:44] - pyatoa - INFO: 
================================================================================
                                    SUMMARY                                     
================================================================================
SOURCE NAME: 002
WINDOWS: 0
RAW MISFIT: 0.0004

================================================================================
                                    RAW LOGS                                    
================================================================================
[2023-05-23 10:38:36] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0001.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:36] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:36] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:36] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:36] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:36] - pyatoa - INFO: gathering data for AA.S0001.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering observed waveforms: AA.S0001.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:36] - pyatoa - INFO: matching observed waveforms found: AA.S0001.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering synthetic waveforms: AA.S0001.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:36] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0001_synthetic_i01s01
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:36] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:36] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0001.BXX.semd
[2023-05-23 10:38:36] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0001.BXZ.semd
[2023-05-23 10:38:36] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0001.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering StationXML for: AA.S0001.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:36] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0001
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:36] - pyatoa - WARNING: Could not find matching StationXML for AA.S0001.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:36] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:36] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:36] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:36] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:36] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:36] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:36] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:36] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:36] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:36] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:36] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:36] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:36] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:36] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:36] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:36] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:36] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:36] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:36] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:36] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:36] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:36] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0002.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:36] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:36] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:36] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:36] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:36] - pyatoa - INFO: gathering data for AA.S0002.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering observed waveforms: AA.S0002.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:36] - pyatoa - INFO: matching observed waveforms found: AA.S0002.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering synthetic waveforms: AA.S0002.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:36] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0002_synthetic_i01s01
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:36] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:36] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0002.BXZ.semd
[2023-05-23 10:38:36] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0002.BXX.semd
[2023-05-23 10:38:36] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0002.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering StationXML for: AA.S0002.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:36] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0002
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:36] - pyatoa - WARNING: Could not find matching StationXML for AA.S0002.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:36] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:36] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:36] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:36] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:36] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:36] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:36] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:36] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:36] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:36] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:36] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:36] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:36] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:36] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:36] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:36] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:36] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:36] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:36] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:36] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:36] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:36] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0003.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:36] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:36] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:36] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:36] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:36] - pyatoa - INFO: gathering data for AA.S0003.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering observed waveforms: AA.S0003.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:36] - pyatoa - INFO: matching observed waveforms found: AA.S0003.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering synthetic waveforms: AA.S0003.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:36] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0003_synthetic_i01s01
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:36] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:36] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0003.BXX.semd
[2023-05-23 10:38:36] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0003.BXZ.semd
[2023-05-23 10:38:36] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0003.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering StationXML for: AA.S0003.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:36] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0003
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:36] - pyatoa - WARNING: Could not find matching StationXML for AA.S0003.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:36] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:36] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:36] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:36] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:36] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:36] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:36] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:36] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:36] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:36] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:36] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:36] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:36] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:36] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:36] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:36] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:36] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:36] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:36] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:36] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:36] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:36] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0004.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:36] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:36] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:36] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:36] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:36] - pyatoa - INFO: gathering data for AA.S0004.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering observed waveforms: AA.S0004.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:36] - pyatoa - INFO: matching observed waveforms found: AA.S0004.*.*
[2023-05-23 10:38:36] - pyatoa - INFO: gathering synthetic waveforms: AA.S0004.*.*
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:36] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0004_synthetic_i01s01
[2023-05-23 10:38:36] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:36] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:36] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0004.BXX.semd
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0004.BXZ.semd
[2023-05-23 10:38:37] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0004.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering StationXML for: AA.S0004.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0004
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:37] - pyatoa - WARNING: Could not find matching StationXML for AA.S0004.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:37] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:37] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:37] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:37] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:37] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:37] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:37] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:37] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:37] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0005.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:37] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:37] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:37] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:37] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:37] - pyatoa - INFO: gathering data for AA.S0005.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering observed waveforms: AA.S0005.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:37] - pyatoa - INFO: matching observed waveforms found: AA.S0005.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering synthetic waveforms: AA.S0005.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0005_synthetic_i01s01
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0005.BXZ.semd
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0005.BXX.semd
[2023-05-23 10:38:37] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0005.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering StationXML for: AA.S0005.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0005
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:37] - pyatoa - WARNING: Could not find matching StationXML for AA.S0005.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:37] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:37] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:37] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:37] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:37] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:37] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:37] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:37] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:37] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0006.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:37] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:37] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:37] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:37] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:37] - pyatoa - INFO: gathering data for AA.S0006.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering observed waveforms: AA.S0006.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:37] - pyatoa - INFO: matching observed waveforms found: AA.S0006.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering synthetic waveforms: AA.S0006.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0006_synthetic_i01s01
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0006.BXX.semd
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0006.BXZ.semd
[2023-05-23 10:38:37] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0006.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering StationXML for: AA.S0006.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0006
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:37] - pyatoa - WARNING: Could not find matching StationXML for AA.S0006.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:37] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:37] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:37] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:37] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:37] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:37] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:37] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:37] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:37] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0007.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:37] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:37] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:37] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:37] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:37] - pyatoa - INFO: gathering data for AA.S0007.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering observed waveforms: AA.S0007.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:37] - pyatoa - INFO: matching observed waveforms found: AA.S0007.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering synthetic waveforms: AA.S0007.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0007_synthetic_i01s01
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0007.BXX.semd
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0007.BXZ.semd
[2023-05-23 10:38:37] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0007.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering StationXML for: AA.S0007.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0007
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:37] - pyatoa - WARNING: Could not find matching StationXML for AA.S0007.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:37] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:37] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:37] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:37] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:37] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:37] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:37] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:37] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:37] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0008.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:37] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:37] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:37] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:37] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:37] - pyatoa - INFO: gathering data for AA.S0008.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering observed waveforms: AA.S0008.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:37] - pyatoa - INFO: matching observed waveforms found: AA.S0008.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering synthetic waveforms: AA.S0008.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0008_synthetic_i01s01
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0008.BXX.semd
[2023-05-23 10:38:37] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0008.BXZ.semd
[2023-05-23 10:38:37] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0008.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering StationXML for: AA.S0008.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0008
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:37] - pyatoa - WARNING: Could not find matching StationXML for AA.S0008.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:37] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:37] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:37] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:37] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:37] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:37] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:37] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:37] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:37] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:37] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:37] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:37] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:37] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:37] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:37] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0009.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:37] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:37] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:37] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:37] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:37] - pyatoa - INFO: gathering data for AA.S0009.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering observed waveforms: AA.S0009.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:37] - pyatoa - INFO: matching observed waveforms found: AA.S0009.*.*
[2023-05-23 10:38:37] - pyatoa - INFO: gathering synthetic waveforms: AA.S0009.*.*
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0009_synthetic_i01s01
[2023-05-23 10:38:37] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:37] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0009.BXX.semd
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0009.BXZ.semd
[2023-05-23 10:38:38] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0009.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering StationXML for: AA.S0009.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0009
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:38] - pyatoa - WARNING: Could not find matching StationXML for AA.S0009.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:38] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:38] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:38] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:38] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:38] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:38] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:38] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:38] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:38] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0010.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:38] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:38] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:38] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:38] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:38] - pyatoa - INFO: gathering data for AA.S0010.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering observed waveforms: AA.S0010.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:38] - pyatoa - INFO: matching observed waveforms found: AA.S0010.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering synthetic waveforms: AA.S0010.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0010_synthetic_i01s01
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0010.BXZ.semd
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0010.BXX.semd
[2023-05-23 10:38:38] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0010.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering StationXML for: AA.S0010.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0010
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:38] - pyatoa - WARNING: Could not find matching StationXML for AA.S0010.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:38] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:38] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:38] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:38] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:38] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:38] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:38] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:38] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:38] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0011.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:38] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:38] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:38] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:38] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:38] - pyatoa - INFO: gathering data for AA.S0011.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering observed waveforms: AA.S0011.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:38] - pyatoa - INFO: matching observed waveforms found: AA.S0011.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering synthetic waveforms: AA.S0011.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0011_synthetic_i01s01
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0011.BXZ.semd
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0011.BXX.semd
[2023-05-23 10:38:38] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0011.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering StationXML for: AA.S0011.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0011
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:38] - pyatoa - WARNING: Could not find matching StationXML for AA.S0011.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:38] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:38] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:38] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:38] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:38] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:38] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:38] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:38] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:38] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0012.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:38] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:38] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:38] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:38] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:38] - pyatoa - INFO: gathering data for AA.S0012.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering observed waveforms: AA.S0012.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:38] - pyatoa - INFO: matching observed waveforms found: AA.S0012.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering synthetic waveforms: AA.S0012.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0012_synthetic_i01s01
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0012.BXX.semd
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0012.BXZ.semd
[2023-05-23 10:38:38] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0012.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering StationXML for: AA.S0012.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0012
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:38] - pyatoa - WARNING: Could not find matching StationXML for AA.S0012.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:38] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:38] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:38] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:38] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:38] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:38] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:38] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:38] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:38] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0013.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:38] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:38] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:38] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:38] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:38] - pyatoa - INFO: gathering data for AA.S0013.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering observed waveforms: AA.S0013.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:38] - pyatoa - INFO: matching observed waveforms found: AA.S0013.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering synthetic waveforms: AA.S0013.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0013_synthetic_i01s01
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0013.BXX.semd
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0013.BXZ.semd
[2023-05-23 10:38:38] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0013.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering StationXML for: AA.S0013.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0013
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:38] - pyatoa - WARNING: Could not find matching StationXML for AA.S0013.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:38] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:38] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:38] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:38] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:38] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:38] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:38] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:38] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:38] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:38] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:38] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:38] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:38] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:38] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:38] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0014.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:38] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:38] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:38] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:38] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:38] - pyatoa - INFO: gathering data for AA.S0014.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering observed waveforms: AA.S0014.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:38] - pyatoa - INFO: matching observed waveforms found: AA.S0014.*.*
[2023-05-23 10:38:38] - pyatoa - INFO: gathering synthetic waveforms: AA.S0014.*.*
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0014_synthetic_i01s01
[2023-05-23 10:38:38] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:38] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:38] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0014.BXX.semd
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0014.BXZ.semd
[2023-05-23 10:38:39] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0014.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering StationXML for: AA.S0014.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0014
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:39] - pyatoa - WARNING: Could not find matching StationXML for AA.S0014.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:39] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:39] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:39] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:39] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:39] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:39] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:39] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:39] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:39] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0015.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:39] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:39] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:39] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:39] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:39] - pyatoa - INFO: gathering data for AA.S0015.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering observed waveforms: AA.S0015.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:39] - pyatoa - INFO: matching observed waveforms found: AA.S0015.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering synthetic waveforms: AA.S0015.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0015_synthetic_i01s01
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0015.BXZ.semd
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0015.BXX.semd
[2023-05-23 10:38:39] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0015.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering StationXML for: AA.S0015.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0015
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:39] - pyatoa - WARNING: Could not find matching StationXML for AA.S0015.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:39] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:39] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:39] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:39] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:39] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:39] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:39] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:39] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:39] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0016.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:39] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:39] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:39] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:39] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:39] - pyatoa - INFO: gathering data for AA.S0016.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering observed waveforms: AA.S0016.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:39] - pyatoa - INFO: matching observed waveforms found: AA.S0016.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering synthetic waveforms: AA.S0016.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0016_synthetic_i01s01
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0016.BXX.semd
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0016.BXZ.semd
[2023-05-23 10:38:39] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0016.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering StationXML for: AA.S0016.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0016
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:39] - pyatoa - WARNING: Could not find matching StationXML for AA.S0016.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:39] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:39] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:39] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:39] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:39] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:39] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:39] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:39] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:39] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0017.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:39] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:39] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:39] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:39] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:39] - pyatoa - INFO: gathering data for AA.S0017.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering observed waveforms: AA.S0017.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:39] - pyatoa - INFO: matching observed waveforms found: AA.S0017.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering synthetic waveforms: AA.S0017.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0017_synthetic_i01s01
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0017.BXX.semd
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0017.BXZ.semd
[2023-05-23 10:38:39] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0017.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering StationXML for: AA.S0017.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0017
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:39] - pyatoa - WARNING: Could not find matching StationXML for AA.S0017.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:39] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:39] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:39] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:39] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:39] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:39] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:39] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:39] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:39] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0018.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:39] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:39] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:39] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:39] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:39] - pyatoa - INFO: gathering data for AA.S0018.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering observed waveforms: AA.S0018.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:39] - pyatoa - INFO: matching observed waveforms found: AA.S0018.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering synthetic waveforms: AA.S0018.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0018_synthetic_i01s01
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0018.BXZ.semd
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0018.BXX.semd
[2023-05-23 10:38:39] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0018.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering StationXML for: AA.S0018.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0018
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:39] - pyatoa - WARNING: Could not find matching StationXML for AA.S0018.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:39] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:39] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:39] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:39] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:39] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:39] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:39] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:39] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:39] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:39] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0019.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:39] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:39] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:39] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:39] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:39] - pyatoa - INFO: gathering data for AA.S0019.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering observed waveforms: AA.S0019.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:39] - pyatoa - INFO: matching observed waveforms found: AA.S0019.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering synthetic waveforms: AA.S0019.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0019_synthetic_i01s01
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:39] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0019.BXZ.semd
[2023-05-23 10:38:39] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0019.BXX.semd
[2023-05-23 10:38:39] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0019.*.*
[2023-05-23 10:38:39] - pyatoa - INFO: gathering StationXML for: AA.S0019.*.*
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:39] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0019
[2023-05-23 10:38:39] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:39] - pyatoa - WARNING: Could not find matching StationXML for AA.S0019.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:39] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:39] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:39] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:39] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:39] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:39] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:39] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:39] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:39] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:39] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:39] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:39] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:40] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:40] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0020.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:40] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:40] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:40] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:40] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:40] - pyatoa - INFO: gathering data for AA.S0020.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering observed waveforms: AA.S0020.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:40] - pyatoa - INFO: matching observed waveforms found: AA.S0020.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering synthetic waveforms: AA.S0020.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0020_synthetic_i01s01
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0020.BXX.semd
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0020.BXZ.semd
[2023-05-23 10:38:40] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0020.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering StationXML for: AA.S0020.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0020
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:40] - pyatoa - WARNING: Could not find matching StationXML for AA.S0020.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:40] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:40] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:40] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:40] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:40] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:40] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:40] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:40] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:40] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0021.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:40] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:40] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:40] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:40] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:40] - pyatoa - INFO: gathering data for AA.S0021.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering observed waveforms: AA.S0021.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:40] - pyatoa - INFO: matching observed waveforms found: AA.S0021.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering synthetic waveforms: AA.S0021.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0021_synthetic_i01s01
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0021.BXZ.semd
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0021.BXX.semd
[2023-05-23 10:38:40] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0021.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering StationXML for: AA.S0021.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0021
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:40] - pyatoa - WARNING: Could not find matching StationXML for AA.S0021.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:40] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:40] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:40] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:40] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:40] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:40] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:40] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:40] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:40] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0022.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:40] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:40] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:40] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:40] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:40] - pyatoa - INFO: gathering data for AA.S0022.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering observed waveforms: AA.S0022.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:40] - pyatoa - INFO: matching observed waveforms found: AA.S0022.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering synthetic waveforms: AA.S0022.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0022_synthetic_i01s01
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0022.BXZ.semd
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0022.BXX.semd
[2023-05-23 10:38:40] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0022.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering StationXML for: AA.S0022.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0022
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:40] - pyatoa - WARNING: Could not find matching StationXML for AA.S0022.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:40] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:40] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:40] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:40] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:40] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:40] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:40] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:40] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:40] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0023.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:40] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:40] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:40] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:40] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:40] - pyatoa - INFO: gathering data for AA.S0023.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering observed waveforms: AA.S0023.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:40] - pyatoa - INFO: matching observed waveforms found: AA.S0023.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering synthetic waveforms: AA.S0023.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0023_synthetic_i01s01
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0023.BXX.semd
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0023.BXZ.semd
[2023-05-23 10:38:40] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0023.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering StationXML for: AA.S0023.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0023
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:40] - pyatoa - WARNING: Could not find matching StationXML for AA.S0023.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:40] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:40] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:40] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:40] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:40] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:40] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:40] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:40] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:40] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:40] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0024.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:40] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:40] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:40] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:40] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:40] - pyatoa - INFO: gathering data for AA.S0024.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering observed waveforms: AA.S0024.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:40] - pyatoa - INFO: matching observed waveforms found: AA.S0024.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering synthetic waveforms: AA.S0024.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0024_synthetic_i01s01
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:40] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0024.BXZ.semd
[2023-05-23 10:38:40] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0024.BXX.semd
[2023-05-23 10:38:40] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0024.*.*
[2023-05-23 10:38:40] - pyatoa - INFO: gathering StationXML for: AA.S0024.*.*
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:40] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0024
[2023-05-23 10:38:40] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:40] - pyatoa - WARNING: Could not find matching StationXML for AA.S0024.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:40] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:40] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:40] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:40] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:40] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:40] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:40] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:40] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:40] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:40] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:40] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:40] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:41] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:41] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0025.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:41] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:41] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:41] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:41] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:41] - pyatoa - INFO: gathering data for AA.S0025.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering observed waveforms: AA.S0025.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:41] - pyatoa - INFO: matching observed waveforms found: AA.S0025.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering synthetic waveforms: AA.S0025.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0025_synthetic_i01s01
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0025.BXZ.semd
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0025.BXX.semd
[2023-05-23 10:38:41] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0025.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering StationXML for: AA.S0025.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0025
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:41] - pyatoa - WARNING: Could not find matching StationXML for AA.S0025.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:41] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:41] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:41] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:41] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:41] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:41] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:41] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:41] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:41] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0026.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:41] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:41] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:41] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:41] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:41] - pyatoa - INFO: gathering data for AA.S0026.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering observed waveforms: AA.S0026.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:41] - pyatoa - INFO: matching observed waveforms found: AA.S0026.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering synthetic waveforms: AA.S0026.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0026_synthetic_i01s01
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0026.BXX.semd
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0026.BXZ.semd
[2023-05-23 10:38:41] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0026.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering StationXML for: AA.S0026.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0026
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:41] - pyatoa - WARNING: Could not find matching StationXML for AA.S0026.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:41] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:41] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:41] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:41] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:41] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:41] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:41] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:41] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:41] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0027.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:41] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:41] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:41] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:41] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:41] - pyatoa - INFO: gathering data for AA.S0027.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering observed waveforms: AA.S0027.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:41] - pyatoa - INFO: matching observed waveforms found: AA.S0027.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering synthetic waveforms: AA.S0027.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0027_synthetic_i01s01
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0027.BXZ.semd
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0027.BXX.semd
[2023-05-23 10:38:41] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0027.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering StationXML for: AA.S0027.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0027
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:41] - pyatoa - WARNING: Could not find matching StationXML for AA.S0027.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:41] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:41] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:41] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:41] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:41] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:41] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:41] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:41] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:41] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0028.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:41] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:41] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:41] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:41] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:41] - pyatoa - INFO: gathering data for AA.S0028.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering observed waveforms: AA.S0028.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:41] - pyatoa - INFO: matching observed waveforms found: AA.S0028.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering synthetic waveforms: AA.S0028.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0028_synthetic_i01s01
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0028.BXX.semd
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0028.BXZ.semd
[2023-05-23 10:38:41] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0028.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering StationXML for: AA.S0028.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0028
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:41] - pyatoa - WARNING: Could not find matching StationXML for AA.S0028.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:41] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:41] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:41] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:41] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:41] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:41] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:41] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:41] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:41] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0029.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:41] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:41] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:41] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:41] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:41] - pyatoa - INFO: gathering data for AA.S0029.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering observed waveforms: AA.S0029.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:41] - pyatoa - INFO: matching observed waveforms found: AA.S0029.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering synthetic waveforms: AA.S0029.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0029_synthetic_i01s01
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0029.BXX.semd
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0029.BXZ.semd
[2023-05-23 10:38:41] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0029.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering StationXML for: AA.S0029.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0029
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:41] - pyatoa - WARNING: Could not find matching StationXML for AA.S0029.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:41] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:41] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:41] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:41] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:41] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:41] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:41] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:41] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:41] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:41] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:41] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:41] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:41] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:41] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:41] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0030.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:41] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:41] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:41] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:41] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:41] - pyatoa - INFO: gathering data for AA.S0030.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering observed waveforms: AA.S0030.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:41] - pyatoa - INFO: matching observed waveforms found: AA.S0030.*.*
[2023-05-23 10:38:41] - pyatoa - INFO: gathering synthetic waveforms: AA.S0030.*.*
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0030_synthetic_i01s01
[2023-05-23 10:38:41] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:41] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:41] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0030.BXZ.semd
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0030.BXX.semd
[2023-05-23 10:38:42] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0030.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering StationXML for: AA.S0030.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0030
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:42] - pyatoa - WARNING: Could not find matching StationXML for AA.S0030.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:42] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:42] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:42] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:42] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:42] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:42] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:42] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:42] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:42] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0031.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:42] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:42] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:42] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:42] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:42] - pyatoa - INFO: gathering data for AA.S0031.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering observed waveforms: AA.S0031.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:42] - pyatoa - INFO: matching observed waveforms found: AA.S0031.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering synthetic waveforms: AA.S0031.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0031_synthetic_i01s01
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0031.BXZ.semd
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0031.BXX.semd
[2023-05-23 10:38:42] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0031.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering StationXML for: AA.S0031.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0031
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:42] - pyatoa - WARNING: Could not find matching StationXML for AA.S0031.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:42] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:42] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:42] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:42] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:42] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:42] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:42] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:42] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:42] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0032.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:42] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:42] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:42] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:42] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:42] - pyatoa - INFO: gathering data for AA.S0032.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering observed waveforms: AA.S0032.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:42] - pyatoa - INFO: matching observed waveforms found: AA.S0032.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering synthetic waveforms: AA.S0032.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0032_synthetic_i01s01
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0032.BXX.semd
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0032.BXZ.semd
[2023-05-23 10:38:42] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0032.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering StationXML for: AA.S0032.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0032
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:42] - pyatoa - WARNING: Could not find matching StationXML for AA.S0032.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:42] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:42] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:42] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:42] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:42] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:42] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:42] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:42] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:42] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0033.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:42] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:42] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:42] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:42] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:42] - pyatoa - INFO: gathering data for AA.S0033.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering observed waveforms: AA.S0033.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:42] - pyatoa - INFO: matching observed waveforms found: AA.S0033.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering synthetic waveforms: AA.S0033.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0033_synthetic_i01s01
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0033.BXX.semd
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0033.BXZ.semd
[2023-05-23 10:38:42] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0033.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering StationXML for: AA.S0033.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0033
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:42] - pyatoa - WARNING: Could not find matching StationXML for AA.S0033.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:42] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:42] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:42] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:42] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:42] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:42] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:42] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:42] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:42] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0034.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:42] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:42] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:42] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:42] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:42] - pyatoa - INFO: gathering data for AA.S0034.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering observed waveforms: AA.S0034.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:42] - pyatoa - INFO: matching observed waveforms found: AA.S0034.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering synthetic waveforms: AA.S0034.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0034_synthetic_i01s01
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0034.BXZ.semd
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0034.BXX.semd
[2023-05-23 10:38:42] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0034.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering StationXML for: AA.S0034.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0034
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:42] - pyatoa - WARNING: Could not find matching StationXML for AA.S0034.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:42] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:42] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:42] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:42] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:42] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:42] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:42] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:42] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:42] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:42] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:42] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:42] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0035.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:42] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:42] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:42] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:42] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:42] - pyatoa - INFO: gathering data for AA.S0035.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering observed waveforms: AA.S0035.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:42] - pyatoa - INFO: matching observed waveforms found: AA.S0035.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering synthetic waveforms: AA.S0035.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0035_synthetic_i01s01
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:42] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0035.BXZ.semd
[2023-05-23 10:38:42] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0035.BXX.semd
[2023-05-23 10:38:42] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0035.*.*
[2023-05-23 10:38:42] - pyatoa - INFO: gathering StationXML for: AA.S0035.*.*
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:42] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0035
[2023-05-23 10:38:42] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:42] - pyatoa - WARNING: Could not find matching StationXML for AA.S0035.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:42] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:42] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:42] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:42] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:42] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:42] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:42] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:42] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:43] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:43] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:43] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:43] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0036.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:43] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:43] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:43] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:43] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:43] - pyatoa - INFO: gathering data for AA.S0036.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering observed waveforms: AA.S0036.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:43] - pyatoa - INFO: matching observed waveforms found: AA.S0036.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering synthetic waveforms: AA.S0036.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0036_synthetic_i01s01
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0036.BXX.semd
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0036.BXZ.semd
[2023-05-23 10:38:43] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0036.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering StationXML for: AA.S0036.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0036
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:43] - pyatoa - WARNING: Could not find matching StationXML for AA.S0036.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:43] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:43] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:43] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:43] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:43] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:43] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:43] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:43] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:43] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0037.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:43] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:43] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:43] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:43] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:43] - pyatoa - INFO: gathering data for AA.S0037.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering observed waveforms: AA.S0037.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:43] - pyatoa - INFO: matching observed waveforms found: AA.S0037.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering synthetic waveforms: AA.S0037.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0037_synthetic_i01s01
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0037.BXZ.semd
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0037.BXX.semd
[2023-05-23 10:38:43] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0037.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering StationXML for: AA.S0037.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0037
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:43] - pyatoa - WARNING: Could not find matching StationXML for AA.S0037.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:43] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:43] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:43] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:43] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:43] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:43] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:43] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:43] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:43] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0038.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:43] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:43] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:43] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:43] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:43] - pyatoa - INFO: gathering data for AA.S0038.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering observed waveforms: AA.S0038.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:43] - pyatoa - INFO: matching observed waveforms found: AA.S0038.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering synthetic waveforms: AA.S0038.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0038_synthetic_i01s01
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0038.BXX.semd
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0038.BXZ.semd
[2023-05-23 10:38:43] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0038.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering StationXML for: AA.S0038.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0038
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:43] - pyatoa - WARNING: Could not find matching StationXML for AA.S0038.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:43] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:43] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:43] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:43] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:43] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:43] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:43] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:43] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:43] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0039.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:43] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:43] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:43] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:43] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:43] - pyatoa - INFO: gathering data for AA.S0039.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering observed waveforms: AA.S0039.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:43] - pyatoa - INFO: matching observed waveforms found: AA.S0039.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering synthetic waveforms: AA.S0039.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0039_synthetic_i01s01
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0039.BXX.semd
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0039.BXZ.semd
[2023-05-23 10:38:43] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0039.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering StationXML for: AA.S0039.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0039
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:43] - pyatoa - WARNING: Could not find matching StationXML for AA.S0039.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:43] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:43] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:43] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:43] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:43] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:43] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:43] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:43] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:43] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
[2023-05-23 10:38:43] - pyatoa - INFO: 
////////////////////////////////////////////////////////////////////////////////
                                  AA.S0040.*.*                                  
////////////////////////////////////////////////////////////////////////////////
[2023-05-23 10:38:43] - pyatoa - INFO: fixed windows flag set constant: False
[2023-05-23 10:38:43] - pyatoa - INFO: gathering event QuakeML
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for event info
[2023-05-23 10:38:43] - pyatoa - DEBUG: event origin time is set to: 1970-01-01T00:00:00.000000Z
[2023-05-23 10:38:43] - pyatoa - INFO: matching event found: '2'
[2023-05-23 10:38:43] - pyatoa - INFO: gathering data for AA.S0040.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering observed waveforms: AA.S0040.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for observations
[2023-05-23 10:38:43] - pyatoa - INFO: matching observed waveforms found: AA.S0040.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering synthetic waveforms: AA.S0040.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching waveform in dataset: AA_S0040_synthetic_i01s01
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for synthetics
[2023-05-23 10:38:43] - pyatoa - DEBUG: found 2 synthetics: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/{net}.{sta}.*{cmp}.sem{dva}*
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0040.BXX.semd
[2023-05-23 10:38:43] - pyatoa - INFO: retrieved synthetics locally: /home/erbiaoger/MyProjects/Seisflows/work/day_3/seisflows_checkboard/scratch/solver/002/traces/syn/AA.S0040.BXZ.semd
[2023-05-23 10:38:43] - pyatoa - DEBUG: matching synthetic waveforms found: AA.S0040.*.*
[2023-05-23 10:38:43] - pyatoa - INFO: gathering StationXML for: AA.S0040.*.*
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching ASDFDataSet for StationXML
[2023-05-23 10:38:43] - pyatoa - DEBUG: no matching inventory in dataset: AA_S0040
[2023-05-23 10:38:43] - pyatoa - DEBUG: searching local filesystem for StationXML
[2023-05-23 10:38:43] - pyatoa - WARNING: Could not find matching StationXML for AA.S0040.*.*, setting 'inv' attribute to None
[2023-05-23 10:38:43] - pyatoa - INFO: standardizing time series
[2023-05-23 10:38:43] - pyatoa - DEBUG: start and endtimes already match to 0.001
[2023-05-23 10:38:43] - pyatoa - INFO: syn time offset == -90.0s
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_obs` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: preprocess `st_syn` as 'syn'
[2023-05-23 10:38:43] - pyatoa - INFO: skip remove response (no `inv`)
[2023-05-23 10:38:43] - pyatoa - INFO: bandpass filter: 10.0 - 200.0s w/ 2 corners
[2023-05-23 10:38:43] - pyatoa - INFO: pyflex preset is set to 'None', will not window
[2023-05-23 10:38:43] - pyatoa - DEBUG: measure misfit of type: waveform
[2023-05-23 10:38:43] - pyatoa - DEBUG: no windows given, adjoint sources will be calculated on full trace
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: X: 0.000 misfit
[2023-05-23 10:38:43] - pyadjoint - INFO: performing misfit caluclation with adjoint source type: `waveform`
[2023-05-23 10:38:43] - pyatoa - INFO: Z: 0.000 misfit
[2023-05-23 10:38:43] - pyatoa - DEBUG: config parameter `save_to_ds` is set False, will not save adjoint sources
[2023-05-23 10:38:43] - pyatoa - INFO: total misfit == 0.000
[2023-05-23 10:38:44] - pyatoa - DEBUG: Event already present, not added
[2023-05-23 10:38:44] - pyatoa - DEBUG: observed waveform already present, not added
[2023-05-23 10:38:44] - pyatoa - DEBUG: saving adjoint sources to ASDFDataSet
